//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by no5_3.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_COLORS                      101
#define IDD_PROPPAGE_PM                 102
#define IDS_YAHOOTXTOBJ_DESC            103
#define IDS_TIMEROBJ_DESC               110
#define IDR_MAINFRAME                   120
#define IDR_MDICHILD                    121
#define IDR_SCRIPTFRAME                 122
#define IDR_PMBOX                       123
#define IDR_TOOLBAR2                    124
#define IDR_TOOLBAR3                    125
#define IDR_FORMFRAME                   126
#define IDS_NAME_USR                    132
#define IDS_NAME_BUD                    133
#define IDS_NAME_ME                     134
#define IDS_TXT_USR                     135
#define IDS_TXT_BUD                     136
#define IDS_TXT_ME                      137
#define IDS_TXT_EMOTE                   138
#define IDS_ENTER_USR                   139
#define IDS_ENTER_BUD                   140
#define IDS_LEAVE_USR                   141
#define IDS_LEAVE_BUD                   142
#define IDS_AWAY_AVAILABLE              143
#define IDS_AWAY_BRB                    144
#define IDS_AWAY_BUSY                   145
#define IDS_AWAY_HOME                   146
#define IDS_AWAY_DESK                   147
#define IDS_AWAY_OFFICE                 148
#define IDS_AWAY_PHONE                  149
#define IDS_AWAY_VACATION               150
#define IDS_AWAY_LUNCH                  151
#define IDS_AWAY_OUT                    152
#define IDS_AWAY_INVISIBLE              153
#define IDS_AWAY_CUSTOM                 154
#define IDS_AWAY_IDLE                   155
#define IDS_AWAY_ON                     156
#define IDS_AWAY_OFF                    157
#define IDS_AWAY_TYPE                   158
#define IDS_AWAY_GAME                   159
#define IDS_IG_FLOOD                    160
#define IDS_IG_BADTAG                   161
#define IDS_IG_REPEAT                   162
#define IDS_IG_SPAM                     163
#define IDS_IG_YBOT                     164
#define IDS_NOYCHT                      165
#define IDR_BOTTOMFRAME                 203
#define IDD_LOGINDLG                    204
#define IDR_USER                        205
#define IDR_PMFRAME                     210
#define IDR_PMBOTTOMFRAME               210
#define IDR_HTML1                       213
#define IDR_HTML_CHAT                   214
#define IDD_ROOMSELECTOR                215
#define IDD_PROPPAGE_GENERAL            216
#define IDR_CHATFRAME                   216
#define IDS_HOMEPAGE                    217
#define IDS_EMAIL                       218
#define IDD_COMPLETE                    223
#define IDD_PROPPAGE_AUTOIGNORE         224
#define IDD_PROPPAGE_PIGNORE            225
#define IDD_PROPPAGE_VISUAL             226
#define IDI_BUD_OFF                     227
#define IDD_INPUT                       229
#define IDD_CAMVIEW                     230
#define IDD_CAMUP                       232
#define IDD_SCRIPTS                     235
#define IDD_BUDDIES                     236
#define IDD_FORMVIEW2                   246
#define IDD_SCRIPTFRAME                 248
#define IDI_STOP                        249
#define IDI_START                       250
#define IDD_FORMLIST                    251
#define IDI_SCRIPT                      252
#define IDI_FORMS                       253
#define IDR_EDIT                        255
#define IDI_CAM                         257
#define IDI_SNAPSHOT                    259
#define IDD_VOICE                       262
#define IDI_TALKING                     267
#define IDC_SCROLLBAR1                  1000
#define IDC_SCROLLBAR2                  1001
#define IDC_SCROLLBAR3                  1002
#define IDC_COMBO1                      1003
#define IDC_COMBO_VIEW                  1004
#define IDC_EDIT_PASSWORD               1005
#define IDC_TREE1                       1006
#define IDC_TREE2                       1007
#define IDC_STATIC_RED                  1008
#define IDC_STATIC_GREEN                1009
#define IDC_STATIC_BLUE                 1010
#define IDC_SIMPLESCRIPTEDITOR1         1011
#define IDC_ID_DELETE                   1012
#define IDC_TOOLBAR_FRAME               1013
#define IDC_ROOM_SELECT                 1014
#define IDC_TOOLBAR_CHAT                1015
#define IDC_COMBO_PROTO                 1016
#define IDC_LIST_COLORS                 1017
#define IDC_CHECK1                      1018
#define ID_COLOR_ADD                    1019
#define IDC_CHECK2                      1020
#define IDC_STATUS                      1021
#define IDC_COMBO_SERVER                1022
#define ID_COLOR_REMOVE                 1023
#define IDC_CHECK3                      1024
#define IDC_STATIC_CODE                 1025
#define IDC_CHECK4                      1026
#define IDC_COMBO_IDS                   1027
#define IDC_COMBO_PORT                  1028
#define ID_COLOR_CLEAR                  1029
#define IDC_COMBO_NAMES                 1030
#define ID_COLORSET_SAVE                1031
#define IDC_STATIC1                     1032
#define IDC_STATIC_COLOR                1033
#define ID_COLORSET_DELETE              1034
#define IDC_BAND_CMDBAR                 1035
#define IDC_BAND_FRAME                  1036
#define IDC_BAND_CHAT                   1037
#define IDC_BAND_MARQUEE                1038
#define IDC_COMBO_ROOM                  1039
#define IDC_MARQUEE1                    1040
#define IDC_LIST1                       1041
#define IDC_CHECK_SPAM                  1042
#define IDC_LIST2                       1043
#define IDC_EDIT1                       1044
#define IDC_BUTTON1                     1045
#define IDC_EDIT_ATIME                  1046
#define IDC_BUTTON2                     1047
#define IDC_SPIN_ATIME                  1048
#define IDC_CHECK_AUTO                  1049
#define IDC_BUTTON3                     1050
#define IDC_CHECK_FLOOD                 1051
#define IDC_BUTTON4                     1052
#define IDC_BUTTON5                     1053
#define IDC_BUTTON6                     1054
#define IDC_BUTTON7                     1055
#define IDC_EDIT_STIME                  1056
#define IDC_BUTTON8                     1057
#define IDC_EDIT_PPS                    1058
#define IDC_STATIC_PREVIEW              1059
#define IDC_BUTTON9                     1060
#define IDC_LABEL1                      1061
#define IDC_WCVIEWER1                   1062
#define IDC_UPLDLG1                     1063
#define IDC_FORMVIEWER1                 1064
#define IDC_COMBO_EVENTS                1065
#define IDC_COMBO_OBJS                  1066
#define ID_FORM_EDIT                    1067
#define ID_FORM_RUN                     1068
#define ID_FORM_RELOAD                  1069
#define IDC_BUTTON_SEND                 1070
#define IDC_FORMEDITOR1                 1071
#define IDC_SCRIPTEDIT                  1072
#define IDC_EDIT_SWORDS                 1073
#define IDC_SNAPSHOT                    1074
#define IDC_RECORD                      1075
#define IDC_CHECK_BADTAG                1076
#define IDC_CHECK_YBOT                  1077
#define IDC_RADIO1                      1078
#define IDC_RADIO2                      1079
#define IDC_RADIO3                      1080
#define IDC_PROGRESS_INPUT              1080
#define IDC_PROGRESS_OUTPUT             1081
#define IDC_BUTTON_TALK                 1082
#define IDC_CHECK_FREE                  1083
#define IDC_BUTTON_CONNECT              1084
#define IDC_LABEL_REPORT                1085
#define IDC_LABEL_TALKING               1086
#define IDC_STATIC2                     1087
#define IDC_STATIC3                     1088
#define IDC_STATIC4                     1089
#define ID_EDIT_COLORS                  32773
#define ID_CUT                          32774
#define ID_COPY                         32775
#define ID_PASTE                        32776
#define ID_UNDO                         32777
#define ID_REDO                         32778
#define ID_FRAME                        32780
#define ID_RECTANGLE                    32781
#define ID_PICTURE                      32782
#define ID_TEXT                         32783
#define ID_BUTTON                       32784
#define ID_CHECK                        32785
#define ID_RADIO                        32786
#define ID_COMBO                        32788
#define ID_LIST                         32789
#define ID_SPIN                         32791
#define ID_SLIDER                       32792
#define ID_PROGRESS                     32793
#define ID_ACTIVEX                      32794
#define ID_FILLER                       32795
#define ID_DELETE                       32795
#define ID_GRID                         32796
#define ID_GRID_SETTINGS                32797
#define ID_TAB                          32798
#define ID_SELECT_ALL                   32799
#define ID_UNSELECT_ALL                 32800
#define ID_PROPERTIES                   32801
#define ID_LEFT                         32802
#define ID_RIGHT                        32803
#define ID_UP                           32804
#define ID_DOWN                         32805
#define ID_ALIGN_LEFT                   32806
#define ID_ALIGN_RIGHT                  32807
#define ID_ALIGN_TOP                    32808
#define ID_ALIGN_BOTTOM                 32809
#define ID_SPACE_HORZ                   32810
#define ID_SPACE_VERT                   32811
#define ID_SIZE_LARGEST_WIDTH           32812
#define ID_SIZE_LARGEST_HEIGHT          32813
#define ID_SIZE_LARGEST                 32814
#define ID_SIZE_SMALLEST_WIDTH          32815
#define ID_SIZE_SMALLEST_HEIGHT         32816
#define ID_SIZE_SMALLEST                32817
#define ID_CENTER_HORZ                  32818
#define ID_CENTER_VERT                  32819
#define ID_CENTER                       32820
#define ID_VALIDATE_SCRIPT              32821
#define ID_PREVIEW_AUTO_SIZE            32822
#define ID_PREVIEW                      32823
#define ID_ROOM_SELECT                  32848
#define ID_FILE_OPTIONS                 32849
#define ID_FILE_CONNECT                 32852
#define ID_ROOM_PREVIOUS                32854
#define ID_ROOM_NEXT                    32855
#define ID_CHAT_LEAVE                   32859
#define ID_CHAT_CHANGEROOM              32860
#define ID_EDIT_COMPLETE                32861
#define ID_SCRIPT_RUN                   32863
#define ID_SCRIPT_STOP                  32864
#define ID_SCRIPT_NEW                   32867
#define ID_LAYOUT_SENDTOBACK            32874
#define ID_BUDDY_REMOVE                 32875
#define ID_LAYOUT_BRINGTOFRONT          32875
#define ID_BUDDY_PM                     32876
#define ID_BUDDY_PROFILE                32877
#define ID_GROUP_RENAME                 32879
#define ID_LABEL                        32879
#define ID_GROUP_ADD                    32880
#define ID_HSCROLL                      32880
#define ID_VSCROLL                      32881
#define ID_CHAT_CAM                     32884
#define ID_BOTTOM_SMILES                32886
#define ID_FORM_NEW                     32887
#define ID_EDIT_BOLD                    32891
#define ID_EDIT_ITALIC                  32892
#define ID_EDIT_UNDERLINE               32893
#define ID_EDIT_FADE                    32894
#define ID_EDIT_BLEND                   32895
#define ID_USER_IGNORE                  32896
#define ID_USER_FOLLOW                  32897
#define ID_USER_CAM                     32898
#define ID_USER_PROFILE                 32899
#define ID_USER_MIMIC                   32900
#define ID_USER_CAMINVITE               32901
#define ID_USER_PM                      32902
#define ID_USER_NAME                    32903
#define ID_VIEW_MARQUEE                 32904
#define ID_USER_BUDDY_ADD               32905
#define ID_USER_BUDDY_REMOVE            32906
#define ID_USER_GOTO                    32907
#define ID_USER_INVITETOTHISROOM        32908
#define ID_USER_INVITE                  32909
#define ID_CHAT_VOICE                   32913
#define ID_CHAT_CONNECT                 32915
#define ID_CHAT_STARTWEBCAM             32916
#define ID_HELP_HOMEPAGE                32917

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        272
#define _APS_NEXT_COMMAND_VALUE         32923
#define _APS_NEXT_CONTROL_VALUE         1090
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
